---
driver:
  name: docker
  use_sudo: false
  privileged: true
  # name: vagrant
  # provider: virtualbox
  # privileged: true
transport:
  name: sftp
platforms:
  - name: ubuntu-20.04
    driver_config:
      run_command: /lib/systemd/systemd
  # - name: debian
  #   driver_config:
  #     run_command: /lib/systemd/systemd
suites:
  - name: apt
verifier:
  name: shell
  remote_exec: false
  command: echo whoami
provisioner:
  name: salt_solo
  salt_install: apt
  salt-version: 3004
  salt_apt_repo: https://repo.saltproject.io/py3/ubuntu/20.04/amd64
  salt_apt_repo_key: https://repo.saltproject.io/py3/ubuntu/20.04/amd64/latest/salt-archive-keyring.gpg
  state_collection: files
  require_chef: false
  salt_copy_filter:
    - .git
    - etc
    - var
    - Saltfile
    - Gemfile
    - salt-server.log
  state_top:
    base:
      "*":
        - tmux
