---
driver:
  name: docker
  use_sudo: false
  privileged: true
  # name: vagrant
  # provider: virtualbox
  # privileged: true
transport:
  name: sftp
platforms:
  - name: ubuntu-2004-3004-1-py3
    driver:
      image: saltimages/salt-3004.1-py3:ubuntu-20.04
      run_command: /lib/systemd/systemd
  # - name: debian
  #   driver_config:
  #     run_command: /lib/systemd/systemd
suites:
  - name: nvim
    provisioner:
      state_top:
        base:
          '*':
            - chezmoi
            - saltlsp
            - nvim
      dependencies:
        - name: node
          repo: git
          source: https://github.com/saltstack-formulas/node-formula.git
      pillars:
        top.sls:
          base:
            '*':
              - node
      pillars_from_files:
        node.sls: pillar/node.sls
  - name: tmux
    provisioner:
      state_top:
        base:
          '*':
            - chezmoi
            - tmux
  - name: rbenv
    provisioner:
      state_top:
        base:
          '*':
            - rbenv
verifier:
  name: shell
  remote_exec: false
  command: echo whoami
provisioner:
  name: salt_solo
  salt_install: none
  # salt-version: 3004
  # salt_apt_repo: https://repo.saltproject.io/py3/ubuntu/20.04/amd64
  # salt_apt_repo_key: https://repo.saltproject.io/py3/ubuntu/20.04/amd64/latest/salt-archive-keyring.gpg
  state_collection: files
  require_chef: false
  salt_copy_filter:
    - .git
    - etc
    - var
    - Saltfile
    - Gemfile
    - salt-server.log
  state_top:
    base:
      "*":
        - tmux
