# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:
  salt-lint:
    runs-on: ubuntu-latest
    name: Salt Lint
    steps:
    - uses: actions/checkout@v1
    - name: Run salt-lint
      uses: roaldnefs/salt-lint-action@master
      env:
        ACTION_STATE_FIND_PATTERN: '^.*\.(sls|jinja|j2|tmpl|tst)$'
        ACTION_STATE_FIND_TYPE: 'regex'
        SALT_LINT_EXTRA_PARAMS: '-v'
  kitchen-salt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6.10']

    steps:
    - uses: actions/checkout@v3
    - run: cd salt
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@2b019609e2b0f1ea1a2bc8ca11cb82ab46ada124
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec kitchen test
